### ISSUE TITLE
Conflict with circle and fading circle

### ISSUE THREAD

**Issue by lingtalfi** [tobiasahlin/SpinKit#141]
Hi, I'm displaying all the spinners in one page, and I noticed that the fading circle appears with an extra margin of 40px. I could fix this easily by adding this rule in my css:

```css
    .sk-fading-circle .sk-circle{
        margin: 0;
    }
```

I belileve this should be part of the distributed spinkit.css.
What happens is that fading circle and circle spinners both use the ".sk-circle" class, and so
if you use a fading spinner using the current spinkit.css (with all spinners merged), you will have an extra (and undesirable) 40px margin.

Hope this helps. Cheers.
